/* eslint-disable global-require */
export const KanaData = {
    // Hiragana
    あ: { kana: 'あ', eng: 'a', audio: require('@/assets/audio/set1/a.mp3') },
    い: { kana: 'い', eng: 'i', audio: require('@/assets/audio/set1/i.mp3') },
    う: { kana: 'う', eng: 'u', audio: require('@/assets/audio/set1/u.mp3') },
    え: { kana: 'え', eng: 'e', audio: require('@/assets/audio/set1/e.mp3') },
    お: { kana: 'お', eng: 'o', audio: require('@/assets/audio/set1/o.mp3') },
    か: { kana: 'か', eng: 'ka', audio: require('@/assets/audio/set1/ka.mp3') },
    き: { kana: 'き', eng: 'ki', audio: require('@/assets/audio/set1/ki.mp3') },
    く: { kana: 'く', eng: 'ku', audio: require('@/assets/audio/set1/ku.mp3') },
    け: { kana: 'け', eng: 'ke', audio: require('@/assets/audio/set1/ke.mp3') },
    こ: { kana: 'こ', eng: 'ko', audio: require('@/assets/audio/set1/ko.mp3') },
    さ: { kana: 'さ', eng: 'sa', audio: require('@/assets/audio/set1/sa.mp3') },
    し: { kana: 'し', eng: 'shi', audio: require('@/assets/audio/set1/shi.mp3') },
    す: { kana: 'す', eng: 'su', audio: require('@/assets/audio/set1/su.mp3') },
    せ: { kana: 'せ', eng: 'se', audio: require('@/assets/audio/set1/se.mp3') },
    そ: { kana: 'そ', eng: 'so', audio: require('@/assets/audio/set1/so.mp3') },
    た: { kana: 'た', eng: 'ta', audio: require('@/assets/audio/set1/ta.mp3') },
    ち: { kana: 'ち', eng: 'chi', audio: require('@/assets/audio/set1/chi.mp3') },
    つ: { kana: 'つ', eng: 'tsu', audio: require('@/assets/audio/set1/tsu.mp3') },
    て: { kana: 'て', eng: 'te', audio: require('@/assets/audio/set1/te.mp3') },
    と: { kana: 'と', eng: 'to', audio: require('@/assets/audio/set1/to.mp3') },
    な: { kana: 'な', eng: 'na', audio: require('@/assets/audio/set1/na.mp3') },
    に: { kana: 'に', eng: 'ni', audio: require('@/assets/audio/set1/ni.mp3') },
    ぬ: { kana: 'ぬ', eng: 'nu', audio: require('@/assets/audio/set1/nu.mp3') },
    ね: { kana: 'ね', eng: 'ne', audio: require('@/assets/audio/set1/ne.mp3') },
    の: { kana: 'の', eng: 'no', audio: require('@/assets/audio/set1/no.mp3') },
    は: { kana: 'は', eng: 'ha', audio: require('@/assets/audio/set1/ha.mp3') },
    ひ: { kana: 'ひ', eng: 'hi', audio: require('@/assets/audio/set1/hi.mp3') },
    ふ: { kana: 'ふ', eng: 'fu', audio: require('@/assets/audio/set1/fu.mp3') },
    へ: { kana: 'へ', eng: 'he', audio: require('@/assets/audio/set1/he.mp3') },
    ほ: { kana: 'ほ', eng: 'ho', audio: require('@/assets/audio/set1/ho.mp3') },
    ま: { kana: 'ま', eng: 'ma', audio: require('@/assets/audio/set1/ma.mp3') },
    み: { kana: 'み', eng: 'mi', audio: require('@/assets/audio/set1/mi.mp3') },
    む: { kana: 'む', eng: 'mu', audio: require('@/assets/audio/set1/mu.mp3') },
    め: { kana: 'め', eng: 'me', audio: require('@/assets/audio/set1/me.mp3') },
    も: { kana: 'も', eng: 'mo', audio: require('@/assets/audio/set1/mo.mp3') },
    や: { kana: 'や', eng: 'ya', audio: require('@/assets/audio/set1/ya.mp3') },
    ゆ: { kana: 'ゆ', eng: 'yu', audio: require('@/assets/audio/set1/yu.mp3') },
    よ: { kana: 'よ', eng: 'yo', audio: require('@/assets/audio/set1/yo.mp3') },
    ら: { kana: 'ら', eng: 'ra', audio: require('@/assets/audio/set1/ra.mp3') },
    り: { kana: 'り', eng: 'ri', audio: require('@/assets/audio/set1/ri.mp3') },
    る: { kana: 'る', eng: 'ru', audio: require('@/assets/audio/set1/ru.mp3') },
    れ: { kana: 'れ', eng: 're', audio: require('@/assets/audio/set1/re.mp3') },
    ろ: { kana: 'ろ', eng: 'ro', audio: require('@/assets/audio/set1/ro.mp3') },
    わ: { kana: 'わ', eng: 'wa', audio: require('@/assets/audio/set1/wa.mp3') },
    を: { kana: 'を', eng: 'wo', audio: require('@/assets/audio/set1/wo.mp3') },
    ん: { kana: 'ん', eng: 'n', audio: require('@/assets/audio/set1/n.mp3') },
    が: { kana: 'が', eng: 'ga', audio: require('@/assets/audio/set1/ga.mp3') },
    ぎ: { kana: 'ぎ', eng: 'gi', audio: require('@/assets/audio/set1/gi.mp3') },
    ぐ: { kana: 'ぐ', eng: 'gu', audio: require('@/assets/audio/set1/gu.mp3') },
    げ: { kana: 'げ', eng: 'ge', audio: require('@/assets/audio/set1/ge.mp3') },
    ご: { kana: 'ご', eng: 'go', audio: require('@/assets/audio/set1/go.mp3') },
    ざ: { kana: 'ざ', eng: 'za', audio: require('@/assets/audio/set1/za.mp3') },
    じ: { kana: 'じ', eng: 'ji', audio: require('@/assets/audio/set1/ji.mp3') },
    ず: { kana: 'ず', eng: 'zu', audio: require('@/assets/audio/set1/zu.mp3') },
    ぜ: { kana: 'ぜ', eng: 'ze', audio: require('@/assets/audio/set1/ze.mp3') },
    ぞ: { kana: 'ぞ', eng: 'zo', audio: require('@/assets/audio/set1/zo.mp3') },
    だ: { kana: 'だ', eng: 'da', audio: require('@/assets/audio/set1/da.mp3') },
    ぢ: { kana: 'ぢ', eng: 'ji', audio: require('@/assets/audio/set1/ji.mp3') },
    づ: { kana: 'づ', eng: 'zu', audio: require('@/assets/audio/set1/zu.mp3') },
    で: { kana: 'で', eng: 'de', audio: require('@/assets/audio/set1/de.mp3') },
    ど: { kana: 'ど', eng: 'do', audio: require('@/assets/audio/set1/do.mp3') },
    ば: { kana: 'ば', eng: 'ba', audio: require('@/assets/audio/set1/ba.mp3') },
    び: { kana: 'び', eng: 'bi', audio: require('@/assets/audio/set1/bi.mp3') },
    ぶ: { kana: 'ぶ', eng: 'bu', audio: require('@/assets/audio/set1/bu.mp3') },
    べ: { kana: 'べ', eng: 'be', audio: require('@/assets/audio/set1/be.mp3') },
    ぼ: { kana: 'ぼ', eng: 'bo', audio: require('@/assets/audio/set1/bo.mp3') },
    ぱ: { kana: 'ぱ', eng: 'pa', audio: require('@/assets/audio/set1/pa.mp3') },
    ぴ: { kana: 'ぴ', eng: 'pi', audio: require('@/assets/audio/set1/pi.mp3') },
    ぷ: { kana: 'ぷ', eng: 'pu', audio: require('@/assets/audio/set1/pu.mp3') },
    ぺ: { kana: 'ぺ', eng: 'pe', audio: require('@/assets/audio/set1/pe.mp3') },
    ぽ: { kana: 'ぽ', eng: 'po', audio: require('@/assets/audio/set1/po.mp3') },
    きゃ: { kana: 'きゃ', eng: 'kya', audio: require('@/assets/audio/set1/kya.mp3') },
    きゅ: { kana: 'きゅ', eng: 'kyu', audio: require('@/assets/audio/set1/kyu.mp3') },
    きょ: { kana: 'きょ', eng: 'kyo', audio: require('@/assets/audio/set1/kyo.mp3') },
    ぎゃ: { kana: 'ぎゃ', eng: 'gya', audio: require('@/assets/audio/set1/gya.mp3') },
    ぎゅ: { kana: 'ぎゅ', eng: 'gyu', audio: require('@/assets/audio/set1/gyu.mp3') },
    ぎょ: { kana: 'ぎょ', eng: 'gyo', audio: require('@/assets/audio/set1/gyo.mp3') },
    しゃ: { kana: 'しゃ', eng: 'sha', audio: require('@/assets/audio/set1/sha.mp3') },
    しゅ: { kana: 'しゅ', eng: 'shu', audio: require('@/assets/audio/set1/shu.mp3') },
    しょ: { kana: 'しょ', eng: 'sho', audio: require('@/assets/audio/set1/sho.mp3') },
    じゃ: { kana: 'じゃ', eng: 'ja', audio: require('@/assets/audio/set1/ja.mp3') },
    じゅ: { kana: 'じゅ', eng: 'ju', audio: require('@/assets/audio/set1/ju.mp3') },
    じょ: { kana: 'じょ', eng: 'jo', audio: require('@/assets/audio/set1/jo.mp3') },
    ちゃ: { kana: 'ちゃ', eng: 'cha', audio: require('@/assets/audio/set1/cha.mp3') },
    ちゅ: { kana: 'ちゅ', eng: 'chu', audio: require('@/assets/audio/set1/chu.mp3') },
    ちょ: { kana: 'ちょ', eng: 'cho', audio: require('@/assets/audio/set1/cho.mp3') },
    にゃ: { kana: 'にゃ', eng: 'nya', audio: require('@/assets/audio/set1/nya.mp3') },
    にゅ: { kana: 'にゅ', eng: 'nyu', audio: require('@/assets/audio/set1/nyu.mp3') },
    にょ: { kana: 'にょ', eng: 'nyo', audio: require('@/assets/audio/set1/nyo.mp3') },
    ひゃ: { kana: 'ひゃ', eng: 'hya', audio: require('@/assets/audio/set1/hya.mp3') },
    ひゅ: { kana: 'ひゅ', eng: 'hyu', audio: require('@/assets/audio/set1/hyu.mp3') },
    ひょ: { kana: 'ひょ', eng: 'hyo', audio: require('@/assets/audio/set1/hyo.mp3') },
    びゃ: { kana: 'びゃ', eng: 'bya', audio: require('@/assets/audio/set1/bya.mp3') },
    びゅ: { kana: 'びゅ', eng: 'byu', audio: require('@/assets/audio/set1/byu.mp3') },
    びょ: { kana: 'びょ', eng: 'byo', audio: require('@/assets/audio/set1/byo.mp3') },
    ぴゃ: { kana: 'ぴゃ', eng: 'pya', audio: require('@/assets/audio/set1/pya.mp3') },
    ぴゅ: { kana: 'ぴゅ', eng: 'pyu', audio: require('@/assets/audio/set1/pyu.mp3') },
    ぴょ: { kana: 'ぴょ', eng: 'pyo', audio: require('@/assets/audio/set1/pyo.mp3') },
    みゃ: { kana: 'みゃ', eng: 'mya', audio: require('@/assets/audio/set1/mya.mp3') },
    みゅ: { kana: 'みゅ', eng: 'myu', audio: require('@/assets/audio/set1/myu.mp3') },
    みょ: { kana: 'みょ', eng: 'myo', audio: require('@/assets/audio/set1/myo.mp3') },
    りゃ: { kana: 'りゃ', eng: 'rya', audio: require('@/assets/audio/set1/rya.mp3') },
    りゅ: { kana: 'りゅ', eng: 'ryu', audio: require('@/assets/audio/set1/ryu.mp3') },
    りょ: { kana: 'りょ', eng: 'ryo', audio: require('@/assets/audio/set1/ryo.mp3') },
    // Katakana
    ア: { kana: 'ア', eng: 'a', audio: require('@/assets/audio/set1/a.mp3') },
    イ: { kana: 'イ', eng: 'i', audio: require('@/assets/audio/set1/i.mp3') },
    ウ: { kana: 'ウ', eng: 'u', audio: require('@/assets/audio/set1/u.mp3') },
    エ: { kana: 'エ', eng: 'e', audio: require('@/assets/audio/set1/e.mp3') },
    オ: { kana: 'オ', eng: 'o', audio: require('@/assets/audio/set1/o.mp3') },
    カ: { kana: 'カ', eng: 'ka', audio: require('@/assets/audio/set1/ka.mp3') },
    キ: { kana: 'キ', eng: 'ki', audio: require('@/assets/audio/set1/ki.mp3') },
    ク: { kana: 'ク', eng: 'ku', audio: require('@/assets/audio/set1/ku.mp3') },
    ケ: { kana: 'ケ', eng: 'ke', audio: require('@/assets/audio/set1/ke.mp3') },
    コ: { kana: 'コ', eng: 'ko', audio: require('@/assets/audio/set1/ko.mp3') },
    ガ: { kana: 'ガ', eng: 'ga', audio: require('@/assets/audio/set1/ga.mp3') },
    ギ: { kana: 'ギ', eng: 'gi', audio: require('@/assets/audio/set1/gi.mp3') },
    グ: { kana: 'グ', eng: 'gu', audio: require('@/assets/audio/set1/gu.mp3') },
    ゲ: { kana: 'ゲ', eng: 'ge', audio: require('@/assets/audio/set1/ge.mp3') },
    ゴ: { kana: 'ゴ', eng: 'go', audio: require('@/assets/audio/set1/go.mp3') },
    サ: { kana: 'サ', eng: 'sa', audio: require('@/assets/audio/set1/sa.mp3') },
    シ: { kana: 'シ', eng: 'shi', audio: require('@/assets/audio/set1/shi.mp3') },
    ス: { kana: 'ス', eng: 'su', audio: require('@/assets/audio/set1/su.mp3') },
    セ: { kana: 'セ', eng: 'se', audio: require('@/assets/audio/set1/se.mp3') },
    ソ: { kana: 'ソ', eng: 'so', audio: require('@/assets/audio/set1/so.mp3') },
    ザ: { kana: 'ザ', eng: 'za', audio: require('@/assets/audio/set1/za.mp3') },
    ジ: { kana: 'ジ', eng: 'ji', audio: require('@/assets/audio/set1/ji.mp3') },
    ズ: { kana: 'ズ', eng: 'zu', audio: require('@/assets/audio/set1/zu.mp3') },
    ゼ: { kana: 'ゼ', eng: 'ze', audio: require('@/assets/audio/set1/ze.mp3') },
    ゾ: { kana: 'ゾ', eng: 'zo', audio: require('@/assets/audio/set1/zo.mp3') },
    タ: { kana: 'タ', eng: 'ta', audio: require('@/assets/audio/set1/ta.mp3') },
    チ: { kana: 'チ', eng: 'chi', audio: require('@/assets/audio/set1/chi.mp3') },
    ツ: { kana: 'ツ', eng: 'tsu', audio: require('@/assets/audio/set1/tsu.mp3') },
    テ: { kana: 'テ', eng: 'te', audio: require('@/assets/audio/set1/te.mp3') },
    ト: { kana: 'ト', eng: 'to', audio: require('@/assets/audio/set1/to.mp3') },
    ダ: { kana: 'ダ', eng: 'da', audio: require('@/assets/audio/set1/da.mp3') },
    ヂ: { kana: 'ヂ', eng: 'ji', audio: require('@/assets/audio/set1/ji.mp3') },
    ヅ: { kana: 'ヅ', eng: 'zu', audio: require('@/assets/audio/set1/zu.mp3') },
    デ: { kana: 'デ', eng: 'de', audio: require('@/assets/audio/set1/de.mp3') },
    ド: { kana: 'ド', eng: 'do', audio: require('@/assets/audio/set1/do.mp3') },
    ナ: { kana: 'ナ', eng: 'na', audio: require('@/assets/audio/set1/na.mp3') },
    ニ: { kana: 'ニ', eng: 'ni', audio: require('@/assets/audio/set1/ni.mp3') },
    ヌ: { kana: 'ヌ', eng: 'nu', audio: require('@/assets/audio/set1/nu.mp3') },
    ネ: { kana: 'ネ', eng: 'ne', audio: require('@/assets/audio/set1/ne.mp3') },
    ノ: { kana: 'ノ', eng: 'no', audio: require('@/assets/audio/set1/no.mp3') },
    ハ: { kana: 'ハ', eng: 'ha', audio: require('@/assets/audio/set1/ha.mp3') },
    ヒ: { kana: 'ヒ', eng: 'hi', audio: require('@/assets/audio/set1/hi.mp3') },
    フ: { kana: 'フ', eng: 'fu', audio: require('@/assets/audio/set1/fu.mp3') },
    ヘ: { kana: 'ヘ', eng: 'he', audio: require('@/assets/audio/set1/he.mp3') },
    ホ: { kana: 'ホ', eng: 'ho', audio: require('@/assets/audio/set1/ho.mp3') },
    バ: { kana: 'バ', eng: 'ba', audio: require('@/assets/audio/set1/ba.mp3') },
    ビ: { kana: 'ビ', eng: 'bi', audio: require('@/assets/audio/set1/bi.mp3') },
    ブ: { kana: 'ブ', eng: 'bu', audio: require('@/assets/audio/set1/bu.mp3') },
    ベ: { kana: 'ベ', eng: 'be', audio: require('@/assets/audio/set1/be.mp3') },
    ボ: { kana: 'ボ', eng: 'bo', audio: require('@/assets/audio/set1/bo.mp3') },
    パ: { kana: 'パ', eng: 'pa', audio: require('@/assets/audio/set1/pa.mp3') },
    ピ: { kana: 'ピ', eng: 'pi', audio: require('@/assets/audio/set1/pi.mp3') },
    プ: { kana: 'プ', eng: 'pu', audio: require('@/assets/audio/set1/pu.mp3') },
    ペ: { kana: 'ペ', eng: 'pe', audio: require('@/assets/audio/set1/pe.mp3') },
    ポ: { kana: 'ポ', eng: 'po', audio: require('@/assets/audio/set1/po.mp3') },
    マ: { kana: 'マ', eng: 'ma', audio: require('@/assets/audio/set1/ma.mp3') },
    ミ: { kana: 'ミ', eng: 'mi', audio: require('@/assets/audio/set1/mi.mp3') },
    ム: { kana: 'ム', eng: 'mu', audio: require('@/assets/audio/set1/mu.mp3') },
    メ: { kana: 'メ', eng: 'me', audio: require('@/assets/audio/set1/me.mp3') },
    モ: { kana: 'モ', eng: 'mo', audio: require('@/assets/audio/set1/mo.mp3') },
    ヤ: { kana: 'ヤ', eng: 'ya', audio: require('@/assets/audio/set1/ya.mp3') },
    ユ: { kana: 'ユ', eng: 'yu', audio: require('@/assets/audio/set1/yu.mp3') },
    ヨ: { kana: 'ヨ', eng: 'yo', audio: require('@/assets/audio/set1/yo.mp3') },
    ラ: { kana: 'ラ', eng: 'ra', audio: require('@/assets/audio/set1/ra.mp3') },
    リ: { kana: 'リ', eng: 'ri', audio: require('@/assets/audio/set1/ri.mp3') },
    ル: { kana: 'ル', eng: 'ru', audio: require('@/assets/audio/set1/ru.mp3') },
    レ: { kana: 'レ', eng: 're', audio: require('@/assets/audio/set1/re.mp3') },
    ロ: { kana: 'ロ', eng: 'ro', audio: require('@/assets/audio/set1/ro.mp3') },
    ワ: { kana: 'ワ', eng: 'wa', audio: require('@/assets/audio/set1/wa.mp3') },
    ヲ: { kana: 'ヲ', eng: 'wo', audio: require('@/assets/audio/set1/wo.mp3') },
    ン: { kana: 'ン', eng: 'n', audio: require('@/assets/audio/set1/n.mp3') },
    キャ: { kana: 'キャ', eng: 'kya', audio: require('@/assets/audio/set1/kya.mp3') },
    キュ: { kana: 'キュ', eng: 'kyu', audio: require('@/assets/audio/set1/kyu.mp3') },
    キョ: { kana: 'キョ', eng: 'kyo', audio: require('@/assets/audio/set1/kyo.mp3') },
    ギャ: { kana: 'ギャ', eng: 'gya', audio: require('@/assets/audio/set1/gya.mp3') },
    ギュ: { kana: 'ギュ', eng: 'gyu', audio: require('@/assets/audio/set1/gyu.mp3') },
    ギョ: { kana: 'ギョ', eng: 'gyo', audio: require('@/assets/audio/set1/gyo.mp3') },
    シャ: { kana: 'シャ', eng: 'sha', audio: require('@/assets/audio/set1/sha.mp3') },
    シュ: { kana: 'シュ', eng: 'shu', audio: require('@/assets/audio/set1/shu.mp3') },
    ショ: { kana: 'ショ', eng: 'sho', audio: require('@/assets/audio/set1/sho.mp3') },
    ジャ: { kana: 'ジャ', eng: 'ja', audio: require('@/assets/audio/set1/ja.mp3') },
    ジュ: { kana: 'ジュ', eng: 'ju', audio: require('@/assets/audio/set1/ju.mp3') },
    ジョ: { kana: 'ジョ', eng: 'jo', audio: require('@/assets/audio/set1/jo.mp3') },
    チャ: { kana: 'チャ', eng: 'cha', audio: require('@/assets/audio/set1/cha.mp3') },
    チュ: { kana: 'チュ', eng: 'chu', audio: require('@/assets/audio/set1/chu.mp3') },
    チョ: { kana: 'チョ', eng: 'cho', audio: require('@/assets/audio/set1/cho.mp3') },
    ニャ: { kana: 'ニャ', eng: 'nya', audio: require('@/assets/audio/set1/nya.mp3') },
    ニュ: { kana: 'ニュ', eng: 'nyu', audio: require('@/assets/audio/set1/nyu.mp3') },
    ニョ: { kana: 'ニョ', eng: 'nyo', audio: require('@/assets/audio/set1/nyo.mp3') },
    ヒャ: { kana: 'ヒャ', eng: 'hya', audio: require('@/assets/audio/set1/hya.mp3') },
    ヒュ: { kana: 'ヒュ', eng: 'hyu', audio: require('@/assets/audio/set1/hyu.mp3') },
    ヒョ: { kana: 'ヒョ', eng: 'hyo', audio: require('@/assets/audio/set1/hyo.mp3') },
    ビャ: { kana: 'ビャ', eng: 'bya', audio: require('@/assets/audio/set1/bya.mp3') },
    ビュ: { kana: 'ビュ', eng: 'byu', audio: require('@/assets/audio/set1/byu.mp3') },
    ビョ: { kana: 'ビョ', eng: 'byo', audio: require('@/assets/audio/set1/byo.mp3') },
    ピャ: { kana: 'ピャ', eng: 'pya', audio: require('@/assets/audio/set1/pya.mp3') },
    ピュ: { kana: 'ピュ', eng: 'pyu', audio: require('@/assets/audio/set1/pyu.mp3') },
    ピョ: { kana: 'ピョ', eng: 'pyo', audio: require('@/assets/audio/set1/pyo.mp3') },
    ミャ: { kana: 'ミャ', eng: 'mya', audio: require('@/assets/audio/set1/mya.mp3') },
    ミュ: { kana: 'ミュ', eng: 'myu', audio: require('@/assets/audio/set1/myu.mp3') },
    ミョ: { kana: 'ミョ', eng: 'myo', audio: require('@/assets/audio/set1/myo.mp3') },
    リャ: { kana: 'リャ', eng: 'rya', audio: require('@/assets/audio/set1/rya.mp3') },
    リュ: { kana: 'リュ', eng: 'ryu', audio: require('@/assets/audio/set1/ryu.mp3') },
    リョ: { kana: 'リョ', eng: 'ryo', audio: require('@/assets/audio/set1/ryo.mp3') },
  };
  
  export const HiraganaGridLayout = [
    ['あ', 'い', 'う', 'え', 'お'],
    ['か', 'き', 'く', 'け', 'こ'],
    ['さ', 'し', 'す', 'せ', 'そ'],
    ['た', 'ち', 'つ', 'て', 'と'],
    ['な', 'に', 'ぬ', 'ね', 'の'],
    ['は', 'ひ', 'ふ', 'へ', 'ほ'],
    ['ま', 'み', 'む', 'め', 'も'],
    ['や', '', 'ゆ', '', 'よ'],
    ['ら', 'り', 'る', 'れ', 'ろ'],
    ['わ', '', '', '', 'を'],
    ['ん', '', '', '', ''],
    ['が', 'ぎ', 'ぐ', 'げ', 'ご'],
    ['ざ', 'じ', 'ず', 'ぜ', 'ぞ'],
    ['だ', 'ぢ', 'づ', 'で', 'ど'],
    ['ば', 'び', 'ぶ', 'べ', 'ぼ'],
    ['ぱ', 'ぴ', 'ぷ', 'ぺ', 'ぽ'],
    ['きゃ', 'きゅ', 'きょ'],
    ['ぎゃ', 'ぎゅ', 'ぎょ'],
    ['しゃ', 'しゅ', 'しょ'],
    ['じゃ', 'じゅ', 'じょ'],
    ['ちゃ', 'ちゅ', 'ちょ'],
    ['にゃ', 'にゅ', 'にょ'],
    ['ひゃ', 'ひゅ', 'ひょ'],
    ['びゃ', 'びゅ', 'びょ'],
    ['ぴゃ', 'ぴゅ', 'ぴょ'],
    ['みゃ', 'みゅ', 'みょ'],
    ['りゃ', 'りゅ', 'りょ'],
  ];
  
  export const KatakanaGridLayout = [
    ['ア', 'イ', 'ウ', 'エ', 'オ'],
    ['カ', 'キ', 'ク', 'ケ', 'コ'],
    ['サ', 'シ', 'ス', 'セ', 'ソ'],
    ['タ', 'チ', 'ツ', 'テ', 'ト'],
    ['ナ', 'ニ', 'ヌ', 'ネ', 'ノ'],
    ['ハ', 'ヒ', 'フ', 'ヘ', 'ホ'],
    ['マ', 'ミ', 'ム', 'メ', 'モ'],
    ['ヤ', '', 'ユ', '', 'ヨ'],
    ['ラ', 'リ', 'ル', 'レ', 'ロ'],
    ['ワ', '', '', '', 'ヲ'],
    ['ン', '', '', '', ''],
    ['ガ', 'ギ', 'グ', 'ゲ', 'ゴ'],
    ['ザ', 'ジ', 'ズ', 'ゼ', 'ゾ'],
    ['ダ', 'ヂ', 'ヅ', 'デ', 'ド'],
    ['バ', 'ビ', 'ブ', 'ベ', 'ボ'],
    ['パ', 'ピ', 'プ', 'ペ', 'ポ'],
    ['キャ', 'キュ', 'キョ'],
    ['ギャ', 'ギュ', 'ギョ'],
    ['シャ', 'シュ', 'ショ'],
    ['ジャ', 'ジュ', 'ジョ'],
    ['チャ', 'チュ', 'チョ'],
    ['ニャ', 'ニュ', 'ニョ'],
    ['ヒャ', 'ヒュ', 'ヒョ'],
    ['ビャ', 'ビュ', 'ビョ'],
    ['ピャ', 'ピュ', 'ピョ'],
    ['ミャ', 'ミュ', 'ミョ'],
    ['リャ', 'リュ', 'リョ'],
  ];
  
  export const HiraganaGojuon = [
    'あ',
    'い',
    'う',
    'え',
    'お',
    'か',
    'き',
    'く',
    'け',
    'こ',
    'さ',
    'し',
    'す',
    'せ',
    'そ',
    'た',
    'ち',
    'つ',
    'て',
    'と',
    'な',
    'に',
    'ぬ',
    'ね',
    'の',
    'は',
    'ひ',
    'ふ',
    'へ',
    'ほ',
    'ま',
    'み',
    'む',
    'め',
    'も',
    'や',
    'ゆ',
    'よ',
    'ら',
    'り',
    'る',
    'れ',
    'ろ',
    'わ',
    'を',
    'ん',
  ];
  
  export const HiraganaDakuten = [
    'が',
    'ぎ',
    'ぐ',
    'げ',
    'ご',
    'ざ',
    'じ',
    'ず',
    'ぜ',
    'ぞ',
    'だ',
    'ぢ',
    'づ',
    'で',
    'ど',
    'ば',
    'び',
    'ぶ',
    'べ',
    'ぼ',
    'ぱ',
    'ぴ',
    'ぷ',
    'ぺ',
    'ぽ',
  ];
  
  export const HiraganaYoon = [
    'きゃ',
    'きゅ',
    'きょ',
    'ぎゃ',
    'ぎゅ',
    'ぎょ',
    'しゃ',
    'しゅ',
    'しょ',
    'じゃ',
    'じゅ',
    'じょ',
    'ちゃ',
    'ちゅ',
    'ちょ',
    'にゃ',
    'にゅ',
    'にょ',
    'ひゃ',
    'ひゅ',
    'ひょ',
    'びゃ',
    'びゅ',
    'びょ',
    'ぴゃ',
    'ぴゅ',
    'ぴょ',
    'みゃ',
    'みゅ',
    'みょ',
    'りゃ',
    'りゅ',
    'りょ',
  ];
  
  export const KatakanaGojuon = [
    'ア',
    'イ',
    'ウ',
    'エ',
    'オ',
    'カ',
    'キ',
    'ク',
    'ケ',
    'コ',
    'サ',
    'シ',
    'ス',
    'セ',
    'ソ',
    'タ',
    'チ',
    'ツ',
    'テ',
    'ト',
    'ナ',
    'ニ',
    'ヌ',
    'ネ',
    'ノ',
    'ハ',
    'ヒ',
    'フ',
    'ヘ',
    'ホ',
    'マ',
    'ミ',
    'ム',
    'メ',
    'モ',
    'ヤ',
    'ユ',
    'ヨ',
    'ラ',
    'リ',
    'ル',
    'レ',
    'ロ',
    'ワ',
    'ヲ',
    'ン',
  ];
  
  export const KatakanaDakuten = [
    'ガ',
    'ギ',
    'グ',
    'ゲ',
    'ゴ',
    'ザ',
    'ジ',
    'ズ',
    'ゼ',
    'ゾ',
    'ダ',
    'ヂ',
    'ヅ',
    'デ',
    'ド',
    'バ',
    'ビ',
    'ブ',
    'ベ',
    'ボ',
    'パ',
    'ピ',
    'プ',
    'ペ',
    'ポ',
  ];
  
  export const KatakanaYoon = [
    'キャ',
    'キュ',
    'キョ',
    'ギャ',
    'ギュ',
    'ギョ',
    'シャ',
    'シュ',
    'ショ',
    'ジャ',
    'ジュ',
    'ジョ',
    'チャ',
    'チュ',
    'チョ',
    'ニャ',
    'ニュ',
    'ニョ',
    'ヒャ',
    'ヒュ',
    'ヒョ',
    'ビャ',
    'ビュ',
    'ビョ',
    'ピャ',
    'ピュ',
    'ピョ',
    'ミャ',
    'ミュ',
    'ミョ',
    'リャ',
    'リュ',
    'リョ',
  ];
  
  export const KanaGridTypes = Object.freeze({
    Hiragana: 'Hiragana',
    Katakana: 'Katakana',
  });
  
  export const KanaGridData = {
    Hiragana: {
      layout: HiraganaGridLayout,
      gojuon: HiraganaGojuon,
      dakuten: HiraganaDakuten,
      yoon: HiraganaYoon,
    },
    Katakana: {
      layout: KatakanaGridLayout,
      gojuon: KatakanaGojuon,
      dakuten: KatakanaDakuten,
      yoon: KatakanaYoon,
    },
  };
  
  class Lesson {
    id;
  
    title;
  
    subtitle;
  
    kana;
  
    constructor(id: any, title: any, subtitle: any, kana: any) {
      this.title = title;
      this.subtitle = subtitle;
      this.kana = kana;
      this.id = id;
    }
  }
  
  export const HiraganaLessons = [
    new Lesson(1, 'Lesson 1', 'あいうえお', ['あ', 'い', 'う', 'え', 'お']),
    new Lesson(2, 'Lesson 2', 'かきくけこ', ['か', 'き', 'く', 'け', 'こ']),
    new Lesson(3, 'Lesson 3', 'さしすせそ', ['さ', 'し', 'す', 'せ', 'そ']),
    new Lesson(4, 'Lesson 4', 'たちつてと', ['た', 'ち', 'つ', 'て', 'と']),
    new Lesson(5, 'Lesson 5', 'なにぬねの', ['な', 'に', 'ぬ', 'ね', 'の']),
    new Lesson(6, 'Lesson 6', 'はひふへほ', ['は', 'ひ', 'ふ', 'へ', 'ほ']),
    new Lesson(7, 'Lesson 7', 'まみむめも', ['ま', 'み', 'む', 'め', 'も']),
    new Lesson(8, 'Lesson 8', 'らりるれろ', ['ら', 'り', 'る', 'れ', 'ろ']),
    new Lesson(9, 'Lesson 9', 'やゆよわをん', ['や', 'ゆ', 'よ', 'わ', 'を', 'ん']),
    new Lesson(10, 'Lesson 10', 'がぎぐげご', ['が', 'ぎ', 'ぐ', 'げ', 'ご']),
    new Lesson(11, 'Lesson 11', 'ざじずぜぞ', ['ざ', 'じ', 'ず', 'ぜ', 'ぞ']),
    new Lesson(12, 'Lesson 12', 'だぢづでど', ['だ', 'ぢ', 'づ', 'で', 'ど']),
    new Lesson(13, 'Lesson 13', 'ばびぶべぼ', ['ば', 'び', 'ぶ', 'べ', 'ぼ']),
    new Lesson(14, 'Lesson 14', 'ぱぴぷぺぽ', ['ぱ', 'ぴ', 'ぷ', 'ぺ', 'ぽ']),
    new Lesson(15, 'Lesson 15', 'きゃきゅきょぎゃぎゅぎょ', [
      'きゃ',
      'きゅ',
      'きょ',
      'ぎゃ',
      'ぎゅ',
      'ぎょ',
    ]),
    new Lesson(16, 'Lesson 16', 'しゃしゅしょじゃじゅじょ', [
      'しゃ',
      'しゅ',
      'しょ',
      'じゃ',
      'じゅ',
      'じょ',
    ]),
    new Lesson(17, 'Lesson 17', 'ちゃちゅちょにゃにゅにょ', [
      'ちゃ',
      'ちゅ',
      'ちょ',
      'にゃ',
      'にゅ',
      'にょ',
    ]),
    new Lesson(18, 'Lesson 18', 'ひゃひゅひょびゃびゅびょぴゃぴゅぴょ', [
      'ひゃ',
      'ひゅ',
      'ひょ',
      'びゃ',
      'びゅ',
      'びょ',
      'ぴゃ',
      'ぴゅ',
      'ぴょ',
    ]),
    new Lesson(19, 'Lesson 19', 'みゃみゅみょりゃりゅりょ', [
      'みゃ',
      'みゅ',
      'みょ',
      'りゃ',
      'りゅ',
      'りょ',
    ]),
  ];
  
  export const KatakanaLessons = [
    new Lesson(20, 'Lesson 1', 'アイウエオ', ['ア', 'イ', 'ウ', 'エ', 'オ']),
    new Lesson(21, 'Lesson 2', 'カキクケコ', ['カ', 'キ', 'ク', 'ケ', 'コ']),
    new Lesson(22, 'Lesson 3', 'サシスセソ', ['サ', 'シ', 'ス', 'セ', 'ソ']),
    new Lesson(23, 'Lesson 4', 'タチツテト', ['タ', 'チ', 'ツ', 'テ', 'ト']),
    new Lesson(24, 'Lesson 5', 'ナニヌネノ', ['ナ', 'ニ', 'ヌ', 'ネ', 'ノ']),
    new Lesson(25, 'Lesson 6', 'ハヒフヘホ', ['ハ', 'ヒ', 'フ', 'ヘ', 'ホ']),
    new Lesson(26, 'Lesson 7', 'マミムメモ', ['マ', 'ミ', 'ム', 'メ', 'モ']),
    new Lesson(27, 'Lesson 8', 'ラリルレロ', ['ラ', 'リ', 'ル', 'レ', 'ロ']),
    new Lesson(28, 'Lesson 9', 'ヤユヨワヲン', ['ヤ', 'ユ', 'ヨ', 'ワ', 'ヲ', 'ン']),
    new Lesson(29, 'Lesson 10', 'ガギグゲゴ', ['ガ', 'ギ', 'グ', 'ゲ', 'ゴ']),
    new Lesson(30, 'Lesson 11', 'ザジズゼゾ', ['ザ', 'ジ', 'ズ', 'ゼ', 'ゾ']),
    new Lesson(31, 'Lesson 12', 'ダヂヅデド', ['ダ', 'ヂ', 'ヅ', 'デ', 'ド']),
    new Lesson(32, 'Lesson 13', 'バビブベボ', ['バ', 'ビ', 'ブ', 'ベ', 'ボ']),
    new Lesson(33, 'Lesson 14', 'パピプペポ', ['パ', 'ピ', 'プ', 'ペ', 'ポ']),
    new Lesson(34, 'Lesson 15', 'キャキュキョギャギュギョ', [
      'キャ',
      'キュ',
      'キョ',
      'ギャ',
      'ギュ',
      'ギョ',
    ]),
    new Lesson(35, 'Lesson 16', 'シャシュショジャジュジョ', [
      'シャ',
      'シュ',
      'ショ',
      'ジャ',
      'ジュ',
      'ジョ',
    ]),
    new Lesson(36, 'Lesson 17', 'チャチュチョニャニュニョ', [
      'チャ',
      'チュ',
      'チョ',
      'ニャ',
      'ニュ',
      'ニョ',
    ]),
    new Lesson(37, 'Lesson 18', 'ヒャヒュヒョビャビュビョピャピュピョ', [
      'ヒャ',
      'ヒュ',
      'ヒョ',
      'ビャ',
      'ビュ',
      'ビョ',
      'ピャ',
      'ピュ',
      'ピョ',
    ]),
    new Lesson(38, 'Lesson 19', 'ミャミュミョリャリュリョ', [
      'ミャ',
      'ミュ',
      'ミョ',
      'リャ',
      'リュ',
      'リョ',
    ]),
  ];