import { MultipleChoicesQuiz, QuizType } from "../constants/QuizDefinitions.d";

function shuffleArray(array: any[]) {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
    return array;
}
export const CharacterQuizBank = {
    HiraganaLearning: {
        quizzes: [
            new MultipleChoicesQuiz(1, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'あ'?", shuffleArray(["a", "i", "u", "e"]), "a", "The correct answer is 'a'"),
            new MultipleChoicesQuiz(2, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'い'?", shuffleArray(["a", "i", "u", "e"]), "i", "The correct answer is 'i'"),
            new MultipleChoicesQuiz(3, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'う'?", shuffleArray(["a", "i", "u", "e"]), "u", "The correct answer is 'u'"),
            new MultipleChoicesQuiz(4, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'え'?", shuffleArray(["a", "i", "u", "e"]), "e", "The correct answer is 'e'"),
            new MultipleChoicesQuiz(5, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'お'?", shuffleArray(["a", "i", "u", "o"]), "o", "The correct answer is 'o'"),
            new MultipleChoicesQuiz(6, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'か'?", shuffleArray(["ka", "ki", "ku", "ke"]), "ka", "The correct answer is 'ka'"),
            new MultipleChoicesQuiz(7, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'き'?", shuffleArray(["ka", "ki", "ku", "ke"]), "ki", "The correct answer is 'ki'"),
            new MultipleChoicesQuiz(8, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'く'?", shuffleArray(["ka", "ki", "ku", "ke"]), "ku", "The correct answer is 'ku'"),
            new MultipleChoicesQuiz(9, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'け'?", shuffleArray(["ka", "ki", "ku", "ke"]), "ke", "The correct answer is 'ke'"),
            new MultipleChoicesQuiz(10, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'こ'?", shuffleArray(["ka", "ki", "ku", "ko"]), "ko", "The correct answer is 'ko'"),
            new MultipleChoicesQuiz(11, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'さ'?", shuffleArray(["sa", "shi", "su", "se"]), "sa", "The correct answer is 'sa'"),
            new MultipleChoicesQuiz(12, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'し'?", shuffleArray(["sa", "shi", "su", "se"]), "shi", "The correct answer is 'shi'"),
            new MultipleChoicesQuiz(13, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'す'?", shuffleArray(["sa", "shi", "su", "se"]), "su", "The correct answer is 'su'"),
            new MultipleChoicesQuiz(14, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'せ'?", shuffleArray(["sa", "shi", "su", "se"]), "se", "The correct answer is 'se'"),
            new MultipleChoicesQuiz(15, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'そ'?", shuffleArray(["sa", "shi", "su", "so"]), "so", "The correct answer is 'so'"),
            new MultipleChoicesQuiz(16, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'た'?", shuffleArray(["ta", "chi", "tsu", "te"]), "ta", "The correct answer is 'ta'"),
            new MultipleChoicesQuiz(17, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ち'?", shuffleArray(["ta", "chi", "tsu", "te"]), "chi", "The correct answer is 'chi'"),
            new MultipleChoicesQuiz(18, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'つ'?", shuffleArray(["ta", "chi", "tsu", "te"]), "tsu", "The correct answer is 'tsu'"),
            new MultipleChoicesQuiz(19, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'て'?", shuffleArray(["ta", "chi", "tsu", "te"]), "te", "The correct answer is 'te'"),
            new MultipleChoicesQuiz(20, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'と'?", shuffleArray(["ta", "chi", "tsu", "to"]), "to", "The correct answer is 'to'"),
            new MultipleChoicesQuiz(21, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'な'?", shuffleArray(["na", "ni", "nu", "ne"]), "na", "The correct answer is 'na'"),
            new MultipleChoicesQuiz(22, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'に'?", shuffleArray(["na", "ni", "nu", "ne"]), "ni", "The correct answer is 'ni'"),
            new MultipleChoicesQuiz(23, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ぬ'?", shuffleArray(["na", "ni", "nu", "ne"]), "nu", "The correct answer is 'nu'"),
            new MultipleChoicesQuiz(24, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ね'?", shuffleArray(["na", "ni", "nu", "ne"]), "ne", "The correct answer is 'ne'"),
            new MultipleChoicesQuiz(25, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'の'?", shuffleArray(["na", "ni", "nu", "no"]), "no", "The correct answer is 'no'"),
            new MultipleChoicesQuiz(26, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'は'?", shuffleArray(["ha", "hi", "fu", "he"]), "ha", "The correct answer is 'ha'"),
            new MultipleChoicesQuiz(27, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ひ'?", shuffleArray(["ha", "hi", "fu", "he"]), "hi", "The correct answer is 'hi'"),
            new MultipleChoicesQuiz(28, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ふ'?", shuffleArray(["ha", "hi", "fu", "he"]), "fu", "The correct answer is 'fu'"),
            new MultipleChoicesQuiz(29, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'へ'?", shuffleArray(["ha", "hi", "fu", "he"]), "he", "The correct answer is 'he'"),
            new MultipleChoicesQuiz(30, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ほ'?", shuffleArray(["ha", "hi", "fu", "ho"]), "ho", "The correct answer is 'ho'"),
            new MultipleChoicesQuiz(31, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ま'?", shuffleArray(["ma", "mi", "mu", "me"]), "ma", "The correct answer is 'ma'"),
            new MultipleChoicesQuiz(32, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'み'?", shuffleArray(["ma", "mi", "mu", "me"]), "mi", "The correct answer is 'mi'"),
            new MultipleChoicesQuiz(33, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'む'?", shuffleArray(["ma", "mi", "mu", "me"]), "mu", "The correct answer is 'mu'"),
            new MultipleChoicesQuiz(34, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'め'?", shuffleArray(["ma", "mi", "mu", "me"]), "me", "The correct answer is 'me'"),
            new MultipleChoicesQuiz(35, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'も'?", shuffleArray(["ma", "mi", "mu", "mo"]), "mo", "The correct answer is 'mo'"),
            new MultipleChoicesQuiz(36, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'や'?", shuffleArray(["ya", "yu", "yo", "ye"]), "ya", "The correct answer is 'ya'"),
            new MultipleChoicesQuiz(37, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ゆ'?", shuffleArray(["ya", "yu", "yo", "ye"]), "yu", "The correct answer is 'yu'"),
            new MultipleChoicesQuiz(38, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'よ'?", shuffleArray(["ya", "yu", "yo", "ye"]), "yo", "The correct answer is 'yo'"),
            new MultipleChoicesQuiz(39, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ら'?", shuffleArray(["ra", "ri", "ru", "re"]), "ra", "The correct answer is 'ra'"),
            new MultipleChoicesQuiz(40, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'り'?", shuffleArray(["ra", "ri", "ru", "re"]), "ri", "The correct answer is 'ri'"),
            new MultipleChoicesQuiz(41, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'る'?", shuffleArray(["ra", "ri", "ru", "re"]), "ru", "The correct answer is 'ru'"),
            new MultipleChoicesQuiz(42, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'れ'?", shuffleArray(["ra", "ri", "ru", "re"]), "re", "The correct answer is 're'"),
            new MultipleChoicesQuiz(43, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ろ'?", shuffleArray(["ra", "ri", "ru", "ro"]), "ro", "The correct answer is 'ro'"),
            new MultipleChoicesQuiz(44, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'わ'?", shuffleArray(["wa", "wo", "wi", "we"]), "wa", "The correct answer is 'wa'"),
            new MultipleChoicesQuiz(45, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'を'?", shuffleArray(["wa", "wo", "wi", "we"]), "wo", "The correct answer is 'wo'"),
            new MultipleChoicesQuiz(46, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ん'?", shuffleArray(["n", "m", "ng", "nn"]), "n", "The correct answer is 'n'"),
            new MultipleChoicesQuiz(47, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'が'?", shuffleArray(["ga", "ka", "gu", "ge"]), "ga", "The correct answer is 'ga'"),
            new MultipleChoicesQuiz(48, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ぎ'?", shuffleArray(["gi", "ki", "gu", "ge"]), "gi", "The correct answer is 'gi'"),
            new MultipleChoicesQuiz(49, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ぐ'?", shuffleArray(["gu", "ku", "ga", "ge"]), "gu", "The correct answer is 'gu'"),
            new MultipleChoicesQuiz(50, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'げ'?", shuffleArray(["ge", "ke", "ga", "gi"]), "ge", "The correct answer is 'ge'"),
            new MultipleChoicesQuiz(51, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ご'?", shuffleArray(["go", "ko", "ga", "gu"]), "go", "The correct answer is 'go'"),
            new MultipleChoicesQuiz(52, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ざ'?", shuffleArray(["za", "sa", "zu", "ze"]), "za", "The correct answer is 'za'"),
            new MultipleChoicesQuiz(53, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'じ'?", shuffleArray(["ji", "shi", "zu", "ze"]), "ji", "The correct answer is 'ji'"),
            new MultipleChoicesQuiz(54, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ず'?", shuffleArray(["zu", "su", "za", "ze"]), "zu", "The correct answer is 'zu'"),
            new MultipleChoicesQuiz(55, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ぜ'?", shuffleArray(["ze", "se", "za", "zu"]), "ze", "The correct answer is 'ze'"),
            new MultipleChoicesQuiz(56, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ぞ'?", shuffleArray(["zo", "so", "za", "zu"]), "zo", "The correct answer is 'zo'"),
            new MultipleChoicesQuiz(57, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'だ'?", shuffleArray(["da", "ta", "du", "de"]), "da", "The correct answer is 'da'"),
            new MultipleChoicesQuiz(58, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ぢ'?", shuffleArray(["ji", "chi", "du", "de"]), "ji", "The correct answer is 'ji'"),
            new MultipleChoicesQuiz(59, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'づ'?", shuffleArray(["zu", "tsu", "da", "de"]), "zu", "The correct answer is 'zu'"),
            new MultipleChoicesQuiz(60, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'で'?", shuffleArray(["de", "te", "da", "di"]), "de", "The correct answer is 'de'"),
            new MultipleChoicesQuiz(61, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ど'?", shuffleArray(["do", "to", "da", "de"]), "do", "The correct answer is 'do'"),
            new MultipleChoicesQuiz(62, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ば'?", shuffleArray(["ba", "pa", "bu", "be"]), "ba", "The correct answer is 'ba'"),
            new MultipleChoicesQuiz(63, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'び'?", shuffleArray(["bi", "pi", "bu", "be"]), "bi", "The correct answer is 'bi'"),
            new MultipleChoicesQuiz(64, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ぶ'?", shuffleArray(["bu", "pu", "ba", "be"]), "bu", "The correct answer is 'bu'"),
            new MultipleChoicesQuiz(65, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'べ'?", shuffleArray(["be", "pe", "ba", "bi"]), "be", "The correct answer is 'be'"),
            new MultipleChoicesQuiz(66, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ぼ'?", shuffleArray(["bo", "po", "ba", "bu"]), "bo", "The correct answer is 'bo'"),
            new MultipleChoicesQuiz(67, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ぱ'?", shuffleArray(["pa", "ba", "pu", "pe"]), "pa", "The correct answer is 'pa'"),
            new MultipleChoicesQuiz(68, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ぴ'?", shuffleArray(["pi", "bi", "pu", "pe"]), "pi", "The correct answer is 'pi'"),
            new MultipleChoicesQuiz(69, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ぷ'?", shuffleArray(["pu", "bu", "pa", "pe"]), "pu", "The correct answer is 'pu'"),
            new MultipleChoicesQuiz(70, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ぺ'?", shuffleArray(["pe", "be", "pa", "pi"]), "pe", "The correct answer is 'pe'"),
            new MultipleChoicesQuiz(71, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ぽ'?", shuffleArray(["po", "bo", "pa", "pu"]), "po", "The correct answer is 'po'"),
            new MultipleChoicesQuiz(72, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'きゃ'?", shuffleArray(["kya", "kyo", "kyu", "ki"]), "kya", "The correct answer is 'kya'"),
            new MultipleChoicesQuiz(73, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'きゅ'?", shuffleArray(["kyu", "kyo", "kya", "ki"]), "kyu", "The correct answer is 'kyu'"),
            new MultipleChoicesQuiz(74, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'きょ'?", shuffleArray(["kyo", "kya", "kyu", "ki"]), "kyo", "The correct answer is 'kyo'"),
            new MultipleChoicesQuiz(75, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'しゃ'?", shuffleArray(["sha", "sho", "shu", "shi"]), "sha", "The correct answer is 'sha'"),
            new MultipleChoicesQuiz(76, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'しゅ'?", shuffleArray(["shu", "sho", "sha", "shi"]), "shu", "The correct answer is 'shu'"),
            new MultipleChoicesQuiz(77, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'しょ'?", shuffleArray(["sho", "sha", "shu", "shi"]), "sho", "The correct answer is 'sho'"),
            new MultipleChoicesQuiz(78, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ちゃ'?", shuffleArray(["cha", "cho", "chu", "chi"]), "cha", "The correct answer is 'cha'"),
            new MultipleChoicesQuiz(79, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ちゅ'?", shuffleArray(["chu", "cho", "cha", "chi"]), "chu", "The correct answer is 'chu'"),
            new MultipleChoicesQuiz(80, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ちょ'?", shuffleArray(["cho", "cha", "chu", "chi"]), "cho", "The correct answer is 'cho'"),
            new MultipleChoicesQuiz(81, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'にゃ'?", shuffleArray(["nya", "nyo", "nyu", "ni"]), "nya", "The correct answer is 'nya'"),
            new MultipleChoicesQuiz(82, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'にゅ'?", shuffleArray(["nyu", "nyo", "nya", "ni"]), "nyu", "The correct answer is 'nyu'"),
            new MultipleChoicesQuiz(83, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'にょ'?", shuffleArray(["nyo", "nya", "nyu", "ni"]), "nyo", "The correct answer is 'nyo'"),
            new MultipleChoicesQuiz(84, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ひゃ'?", shuffleArray(["hya", "hyo", "hyu", "hi"]), "hya", "The correct answer is 'hya'"),
            new MultipleChoicesQuiz(85, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ひゅ'?", shuffleArray(["hyu", "hyo", "hya", "hi"]), "hyu", "The correct answer is 'hyu'"),
            new MultipleChoicesQuiz(86, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ひょ'?", shuffleArray(["hyo", "hya", "hyu", "hi"]), "hyo", "The correct answer is 'hyo'"),
            new MultipleChoicesQuiz(87, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'みゃ'?", shuffleArray(["mya", "myo", "myu", "mi"]), "mya", "The correct answer is 'mya'"),
            new MultipleChoicesQuiz(88, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'みゅ'?", shuffleArray(["myu", "myo", "mya", "mi"]), "myu", "The correct answer is 'myu'"),
            new MultipleChoicesQuiz(89, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'みょ'?", shuffleArray(["myo", "mya", "myu", "mi"]), "myo", "The correct answer is 'myo'"),
            new MultipleChoicesQuiz(90, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'りゃ'?", shuffleArray(["rya", "ryo", "ryu", "ri"]), "rya", "The correct answer is 'rya'"),
            new MultipleChoicesQuiz(91, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'りゅ'?", shuffleArray(["ryu", "ryo", "rya", "ri"]), "ryu", "The correct answer is 'ryu'"),
            new MultipleChoicesQuiz(92, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'りょ'?", shuffleArray(["ryo", "rya", "ryu", "ri"]), "ryo", "The correct answer is 'ryo'"),
            new MultipleChoicesQuiz(93, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ぎゃ'?", shuffleArray(["gya", "gyo", "gyu", "gi"]), "gya", "The correct answer is 'gya'"),
            new MultipleChoicesQuiz(94, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ぎゅ'?", shuffleArray(["gyu", "gyo", "gya", "gi"]), "gyu", "The correct answer is 'gyu'"),
            new MultipleChoicesQuiz(95, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ぎょ'?", shuffleArray(["gyo", "gya", "gyu", "gi"]), "gyo", "The correct answer is 'gyo'"),
            new MultipleChoicesQuiz(96, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'じゃ'?", shuffleArray(["ja", "jo", "ju", "ji"]), "ja", "The correct answer is 'ja'"),
            new MultipleChoicesQuiz(97, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'じゅ'?", shuffleArray(["ju", "jo", "ja", "ji"]), "ju", "The correct answer is 'ju'"),
            new MultipleChoicesQuiz(98, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'じょ'?", shuffleArray(["jo", "ja", "ju", "ji"]), "jo", "The correct answer is 'jo'"),
            new MultipleChoicesQuiz(99, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'びゃ'?", shuffleArray(["bya", "byo", "byu", "bi"]), "bya", "The correct answer is 'bya'"),
            new MultipleChoicesQuiz(100, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'びゅ'?", shuffleArray(["byu", "byo", "bya", "bi"]), "byu", "The correct answer is 'byu'"),
            new MultipleChoicesQuiz(101, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'びょ'?", shuffleArray(["byo", "bya", "byu", "bi"]), "byo", "The correct answer is 'byo'"),
            new MultipleChoicesQuiz(102, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ぴゃ'?", shuffleArray(["pya", "pyo", "pyu", "pi"]), "pya", "The correct answer is 'pya'"),
            new MultipleChoicesQuiz(103, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ぴゅ'?", shuffleArray(["pyu", "pyo", "pya", "pi"]), "pyu", "The correct answer is 'pyu'"),
            new MultipleChoicesQuiz(104, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ぴょ'?", shuffleArray(["pyo", "pya", "pyu", "pi"]), "pyo", "The correct answer is 'pyo'")
        ]
    },
    KatakanaLearning: {
        quizzes: [
            new MultipleChoicesQuiz(1, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ア'?", shuffleArray(["a", "i", "u", "e"]), "a", "The correct answer is 'a'"),
            new MultipleChoicesQuiz(2, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'イ'?", shuffleArray(["a", "i", "u", "e"]), "i", "The correct answer is 'i'"),
            new MultipleChoicesQuiz(3, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ウ'?", shuffleArray(["a", "i", "u", "e"]), "u", "The correct answer is 'u'"),
            new MultipleChoicesQuiz(4, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'エ'?", shuffleArray(["a", "i", "u", "e"]), "e", "The correct answer is 'e'"),
            new MultipleChoicesQuiz(5, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'オ'?", shuffleArray(["a", "i", "u", "o"]), "o", "The correct answer is 'o'"),
            new MultipleChoicesQuiz(6, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'カ'?", shuffleArray(["ka", "ki", "ku", "ke"]), "ka", "The correct answer is 'ka'"),
            new MultipleChoicesQuiz(7, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'キ'?", shuffleArray(["ka", "ki", "ku", "ke"]), "ki", "The correct answer is 'ki'"),
            new MultipleChoicesQuiz(8, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ク'?", shuffleArray(["ka", "ki", "ku", "ke"]), "ku", "The correct answer is 'ku'"),
            new MultipleChoicesQuiz(9, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ケ'?", shuffleArray(["ka", "ki", "ku", "ke"]), "ke", "The correct answer is 'ke'"),
            new MultipleChoicesQuiz(10, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'コ'?", shuffleArray(["ka", "ki", "ku", "ko"]), "ko", "The correct answer is 'ko'"),
            new MultipleChoicesQuiz(11, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'サ'?", shuffleArray(["sa", "shi", "su", "se"]), "sa", "The correct answer is 'sa'"),
            new MultipleChoicesQuiz(12, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'シ'?", shuffleArray(["sa", "shi", "su", "se"]), "shi", "The correct answer is 'shi'"),
            new MultipleChoicesQuiz(13, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ス'?", shuffleArray(["sa", "shi", "su", "se"]), "su", "The correct answer is 'su'"),
            new MultipleChoicesQuiz(14, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'セ'?", shuffleArray(["sa", "shi", "su", "se"]), "se", "The correct answer is 'se'"),
            new MultipleChoicesQuiz(15, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ソ'?", shuffleArray(["sa", "shi", "su", "so"]), "so", "The correct answer is 'so'"),
            new MultipleChoicesQuiz(16, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'タ'?", shuffleArray(["ta", "chi", "tsu", "te"]), "ta", "The correct answer is 'ta'"),
            new MultipleChoicesQuiz(17, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'チ'?", shuffleArray(["ta", "chi", "tsu", "te"]), "chi", "The correct answer is 'chi'"),
            new MultipleChoicesQuiz(18, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ツ'?", shuffleArray(["ta", "chi", "tsu", "te"]), "tsu", "The correct answer is 'tsu'"),
            new MultipleChoicesQuiz(19, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'テ'?", shuffleArray(["ta", "chi", "tsu", "te"]), "te", "The correct answer is 'te'"),
            new MultipleChoicesQuiz(20, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ト'?", shuffleArray(["ta", "chi", "tsu", "to"]), "to", "The correct answer is 'to'"),
            new MultipleChoicesQuiz(21, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ナ'?", shuffleArray(["na", "ni", "nu", "ne"]), "na", "The correct answer is 'na'"),
            new MultipleChoicesQuiz(22, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ニ'?", shuffleArray(["na", "ni", "nu", "ne"]), "ni", "The correct answer is 'ni'"),
            new MultipleChoicesQuiz(23, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ヌ'?", shuffleArray(["na", "ni", "nu", "ne"]), "nu", "The correct answer is 'nu'"),
            new MultipleChoicesQuiz(24, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ネ'?", shuffleArray(["na", "ni", "nu", "ne"]), "ne", "The correct answer is 'ne'"),
            new MultipleChoicesQuiz(25, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ノ'?", shuffleArray(["na", "ni", "nu", "no"]), "no", "The correct answer is 'no'"),
            new MultipleChoicesQuiz(26, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ハ'?", shuffleArray(["ha", "hi", "fu", "he"]), "ha", "The correct answer is 'ha'"),
            new MultipleChoicesQuiz(27, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ヒ'?", shuffleArray(["ha", "hi", "fu", "he"]), "hi", "The correct answer is 'hi'"),
            new MultipleChoicesQuiz(28, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'フ'?", shuffleArray(["ha", "hi", "fu", "he"]), "fu", "The correct answer is 'fu'"),
            new MultipleChoicesQuiz(29, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ヘ'?", shuffleArray(["ha", "hi", "fu", "he"]), "he", "The correct answer is 'he'"),
            new MultipleChoicesQuiz(30, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ホ'?", shuffleArray(["ha", "hi", "fu", "ho"]), "ho", "The correct answer is 'ho'"),
            new MultipleChoicesQuiz(31, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'マ'?", shuffleArray(["ma", "mi", "mu", "me"]), "ma", "The correct answer is 'ma'"),
            new MultipleChoicesQuiz(32, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ミ'?", shuffleArray(["ma", "mi", "mu", "me"]), "mi", "The correct answer is 'mi'"),
            new MultipleChoicesQuiz(33, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ム'?", shuffleArray(["ma", "mi", "mu", "me"]), "mu", "The correct answer is 'mu'"),
            new MultipleChoicesQuiz(34, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'メ'?", shuffleArray(["ma", "mi", "mu", "me"]), "me", "The correct answer is 'me'"),
            new MultipleChoicesQuiz(35, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'モ'?", shuffleArray(["ma", "mi", "mu", "mo"]), "mo", "The correct answer is 'mo'"),
            new MultipleChoicesQuiz(36, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ヤ'?", shuffleArray(["ya", "yu", "yo", "ye"]), "ya", "The correct answer is 'ya'"),
            new MultipleChoicesQuiz(37, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ユ'?", shuffleArray(["ya", "yu", "yo", "ye"]), "yu", "The correct answer is 'yu'"),
            new MultipleChoicesQuiz(38, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ヨ'?", shuffleArray(["ya", "yu", "yo", "ye"]), "yo", "The correct answer is 'yo'"),
            new MultipleChoicesQuiz(39, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ラ'?", shuffleArray(["ra", "ri", "ru", "re"]), "ra", "The correct answer is 'ra'"),
            new MultipleChoicesQuiz(40, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'リ'?", shuffleArray(["ra", "ri", "ru", "re"]), "ri", "The correct answer is 'ri'"),
            new MultipleChoicesQuiz(41, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ル'?", shuffleArray(["ra", "ri", "ru", "re"]), "ru", "The correct answer is 'ru'"),
            new MultipleChoicesQuiz(42, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'レ'?", shuffleArray(["ra", "ri", "ru", "re"]), "re", "The correct answer is 're'"),
            new MultipleChoicesQuiz(43, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ロ'?", shuffleArray(["ra", "ri", "ru", "ro"]), "ro", "The correct answer is 'ro'"),
            new MultipleChoicesQuiz(44, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ワ'?", shuffleArray(["wa", "wo", "we", "wi"]), "wa", "The correct answer is 'wa'"),
            new MultipleChoicesQuiz(45, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ヲ'?", shuffleArray(["wa", "wo", "we", "wi"]), "wo", "The correct answer is 'wo'"),
            new MultipleChoicesQuiz(46, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ン'?", shuffleArray(["n", "m", "r", "l"]), "n", "The correct answer is 'n'"),
            new MultipleChoicesQuiz(47, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ガ'?", shuffleArray(["ga", "ka", "gu", "ge"]), "ga", "The correct answer is 'ga'"),
            new MultipleChoicesQuiz(48, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ギ'?", shuffleArray(["gi", "ki", "gu", "ge"]), "gi", "The correct answer is 'gi'"),
            new MultipleChoicesQuiz(49, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'グ'?", shuffleArray(["gu", "ku", "ga", "ge"]), "gu", "The correct answer is 'gu'"),
            new MultipleChoicesQuiz(50, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ゲ'?", shuffleArray(["ge", "ke", "ga", "gi"]), "ge", "The correct answer is 'ge'"),
            new MultipleChoicesQuiz(51, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ゴ'?", shuffleArray(["go", "ko", "ga", "gu"]), "go", "The correct answer is 'go'"),
            new MultipleChoicesQuiz(52, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ザ'?", shuffleArray(["za", "sa", "zu", "ze"]), "za", "The correct answer is 'za'"),
            new MultipleChoicesQuiz(53, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ジ'?", shuffleArray(["ji", "shi", "zu", "ze"]), "ji", "The correct answer is 'ji'"),
            new MultipleChoicesQuiz(54, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ズ'?", shuffleArray(["zu", "su", "za", "ze"]), "zu", "The correct answer is 'zu'"),
            new MultipleChoicesQuiz(55, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ゼ'?", shuffleArray(["ze", "se", "za", "zu"]), "ze", "The correct answer is 'ze'"),
            new MultipleChoicesQuiz(56, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ゾ'?", shuffleArray(["zo", "so", "za", "zu"]), "zo", "The correct answer is 'zo'"),
            new MultipleChoicesQuiz(57, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ダ'?", shuffleArray(["da", "ta", "du", "de"]), "da", "The correct answer is 'da'"),
            new MultipleChoicesQuiz(58, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ヂ'?", shuffleArray(["ji", "chi", "du", "de"]), "ji", "The correct answer is 'ji'"),
            new MultipleChoicesQuiz(59, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ヅ'?", shuffleArray(["zu", "tsu", "da", "de"]), "zu", "The correct answer is 'zu'"),
            new MultipleChoicesQuiz(60, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'デ'?", shuffleArray(["de", "te", "da", "di"]), "de", "The correct answer is 'de'"),
            new MultipleChoicesQuiz(61, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ド'?", shuffleArray(["do", "to", "da", "de"]), "do", "The correct answer is 'do'"),
            new MultipleChoicesQuiz(62, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'バ'?", shuffleArray(["ba", "pa", "bu", "be"]), "ba", "The correct answer is 'ba'"),
            new MultipleChoicesQuiz(63, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ビ'?", shuffleArray(["bi", "pi", "bu", "be"]), "bi", "The correct answer is 'bi'"),
            new MultipleChoicesQuiz(64, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ブ'?", shuffleArray(["bu", "pu", "ba", "be"]), "bu", "The correct answer is 'bu'"),
            new MultipleChoicesQuiz(65, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ベ'?", shuffleArray(["be", "pe", "ba", "bi"]), "be", "The correct answer is 'be'"),
            new MultipleChoicesQuiz(66, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ボ'?", shuffleArray(["bo", "po", "ba", "bu"]), "bo", "The correct answer is 'bo'"),
            new MultipleChoicesQuiz(67, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'パ'?", shuffleArray(["pa", "ba", "pu", "pe"]), "pa", "The correct answer is 'pa'"),
            new MultipleChoicesQuiz(68, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ピ'?", shuffleArray(["pi", "bi", "pu", "pe"]), "pi", "The correct answer is 'pi'"),
            new MultipleChoicesQuiz(69, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'プ'?", shuffleArray(["pu", "bu", "pa", "pe"]), "pu", "The correct answer is 'pu'"),
            new MultipleChoicesQuiz(70, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ペ'?", shuffleArray(["pe", "be", "pa", "pi"]), "pe", "The correct answer is 'pe'"),
            new MultipleChoicesQuiz(71, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ポ'?", shuffleArray(["po", "bo", "pa", "pu"]), "po", "The correct answer is 'po'"),
            new MultipleChoicesQuiz(72, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'キャ'?", shuffleArray(["kya", "kyo", "kyu", "ki"]), "kya", "The correct answer is 'kya'"),
            new MultipleChoicesQuiz(73, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'キュ'?", shuffleArray(["kyu", "kyo", "kya", "ki"]), "kyu", "The correct answer is 'kyu'"),
            new MultipleChoicesQuiz(74, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'キョ'?", shuffleArray(["kyo", "kya", "kyu", "ki"]), "kyo", "The correct answer is 'kyo'"),
            new MultipleChoicesQuiz(75, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'シャ'?", shuffleArray(["sha", "sho", "shu", "shi"]), "sha", "The correct answer is 'sha'"),
            new MultipleChoicesQuiz(76, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'シュ'?", shuffleArray(["shu", "sho", "sha", "shi"]), "shu", "The correct answer is 'shu'"),
            new MultipleChoicesQuiz(77, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ショ'?", shuffleArray(["sho", "sha", "shu", "shi"]), "sho", "The correct answer is 'sho'"),
            new MultipleChoicesQuiz(78, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'チャ'?", shuffleArray(["cha", "cho", "chu", "chi"]), "cha", "The correct answer is 'cha'"),
            new MultipleChoicesQuiz(79, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'チュ'?", shuffleArray(["chu", "cho", "cha", "chi"]), "chu", "The correct answer is 'chu'"),
            new MultipleChoicesQuiz(80, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'チョ'?", shuffleArray(["cho", "cha", "chu", "chi"]), "cho", "The correct answer is 'cho'"),
            new MultipleChoicesQuiz(81, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ニャ'?", shuffleArray(["nya", "nyo", "nyu", "ni"]), "nya", "The correct answer is 'nya'"),
            new MultipleChoicesQuiz(82, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ニュ'?", shuffleArray(["nyu", "nyo", "nya", "ni"]), "nyu", "The correct answer is 'nyu'"),
            new MultipleChoicesQuiz(83, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ニョ'?", shuffleArray(["nyo", "nya", "nyu", "ni"]), "nyo", "The correct answer is 'nyo'"),
            new MultipleChoicesQuiz(84, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ヒャ'?", shuffleArray(["hya", "hyo", "hyu", "hi"]), "hya", "The correct answer is 'hya'"),
            new MultipleChoicesQuiz(85, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ヒュ'?", shuffleArray(["hyu", "hyo", "hya", "hi"]), "hyu", "The correct answer is 'hyu'"),
            new MultipleChoicesQuiz(86, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ヒョ'?", shuffleArray(["hyo", "hya", "hyu", "hi"]), "hyo", "The correct answer is 'hyo'"),
            new MultipleChoicesQuiz(87, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ミャ'?", shuffleArray(["mya", "myo", "myu", "mi"]), "mya", "The correct answer is 'mya'"),
            new MultipleChoicesQuiz(88, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ミュ'?", shuffleArray(["myu", "myo", "mya", "mi"]), "myu", "The correct answer is 'myu'"),
            new MultipleChoicesQuiz(89, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ミョ'?", shuffleArray(["myo", "mya", "myu", "mi"]), "myo", "The correct answer is 'myo'"),
            new MultipleChoicesQuiz(90, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'リャ'?", shuffleArray(["rya", "ryo", "ryu", "ri"]), "rya", "The correct answer is 'rya'"),
            new MultipleChoicesQuiz(91, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'リュ'?", shuffleArray(["ryu", "ryo", "rya", "ri"]), "ryu", "The correct answer is 'ryu'"),
            new MultipleChoicesQuiz(92, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'リョ'?", shuffleArray(["ryo", "rya", "ryu", "ri"]), "ryo", "The correct answer is 'ryo'"),
            new MultipleChoicesQuiz(93, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ギャ'?", shuffleArray(["gya", "gyo", "gyu", "gi"]), "gya", "The correct answer is 'gya'"),
            new MultipleChoicesQuiz(94, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ギュ'?", shuffleArray(["gyu", "gyo", "gya", "gi"]), "gyu", "The correct answer is 'gyu'"),
            new MultipleChoicesQuiz(95, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ギョ'?", shuffleArray(["gyo", "gya", "gyu", "gi"]), "gyo", "The correct answer is 'gyo'"),
            new MultipleChoicesQuiz(96, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ジャ'?", shuffleArray(["ja", "jo", "ju", "ji"]), "ja", "The correct answer is 'ja'"),
            new MultipleChoicesQuiz(97, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ジュ'?", shuffleArray(["ju", "jo", "ja", "ji"]), "ju", "The correct answer is 'ju'"),
            new MultipleChoicesQuiz(98, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ジョ'?", shuffleArray(["jo", "ja", "ju", "ji"]), "jo", "The correct answer is 'jo'"),
            new MultipleChoicesQuiz(99, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ビャ'?", shuffleArray(["bya", "byo", "byu", "bi"]), "bya", "The correct answer is 'bya'"),
            new MultipleChoicesQuiz(100, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ビュ'?", shuffleArray(["byu", "byo", "bya", "bi"]), "byu", "The correct answer is 'byu'"),
            new MultipleChoicesQuiz(101, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ビョ'?", shuffleArray(["byo", "bya", "byu", "bi"]), "byo", "The correct answer is 'byo'"),
            new MultipleChoicesQuiz(102, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ピャ'?", shuffleArray(["pya", "pyo", "pyu", "pi"]), "pya", "The correct answer is 'pya'"),
            new MultipleChoicesQuiz(103, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ピュ'?", shuffleArray(["pyu", "pyo", "pya", "pi"]), "pyu", "The correct answer is 'pyu'"),
            new MultipleChoicesQuiz(104, QuizType.CHARACTERS_LEARNING, "What is the romaji for 'ピョ'?", shuffleArray(["pyo", "pya", "pyu", "pi"]), "pyo", "The correct answer is 'pyo'")
        ]
    }
}
export const LessonQuizBank = {
    lesson1: {
        quizzes: [
            // CHARACTERS_LEARNING (N5 Vocabulary with yomikata)
        new MultipleChoicesQuiz(1, QuizType.CHARACTERS_LEARNING, "What is the meaning of '学校' (がっこう)?", shuffleArray(["school", "teacher", "student", "classroom"]), "school", "The correct answer is 'school'"),
        new MultipleChoicesQuiz(2, QuizType.CHARACTERS_LEARNING, "What is the meaning of '先生' (せんせい)?", shuffleArray(["teacher", "student", "school", "classroom"]), "teacher", "The correct answer is 'teacher'"),
        new MultipleChoicesQuiz(3, QuizType.CHARACTERS_LEARNING, "What is the meaning of '学生' (がくせい)?", shuffleArray(["student", "teacher", "school", "classroom"]), "student", "The correct answer is 'student'"),
        new MultipleChoicesQuiz(4, QuizType.CHARACTERS_LEARNING, "What is the meaning of '教室' (きょうしつ)?", shuffleArray(["classroom", "teacher", "student", "school"]), "classroom", "The correct answer is 'classroom'"),
        new MultipleChoicesQuiz(5, QuizType.CHARACTERS_LEARNING, "What is the meaning of '本' (ほん)?", shuffleArray(["book", "pen", "notebook", "pencil"]), "book", "The correct answer is 'book'"),
        new MultipleChoicesQuiz(6, QuizType.CHARACTERS_LEARNING, "What is the meaning of '犬' (いぬ)?", shuffleArray(["dog", "cat", "bird", "fish"]), "dog", "The correct answer is 'dog'"),
        new MultipleChoicesQuiz(7, QuizType.CHARACTERS_LEARNING, "What is the meaning of '猫' (ねこ)?", shuffleArray(["cat", "dog", "bird", "fish"]), "cat", "The correct answer is 'cat'"),
        new MultipleChoicesQuiz(8, QuizType.CHARACTERS_LEARNING, "What is the meaning of '車' (くるま)?", shuffleArray(["car", "bicycle", "bus", "train"]), "car", "The correct answer is 'car'"),
        new MultipleChoicesQuiz(9, QuizType.CHARACTERS_LEARNING, "What is the meaning of '電車' (でんしゃ)?", shuffleArray(["train", "car", "bicycle", "bus"]), "train", "The correct answer is 'train'"),
        new MultipleChoicesQuiz(10, QuizType.CHARACTERS_LEARNING, "What is the meaning of '駅' (えき)?", shuffleArray(["station", "bus stop", "airport", "port"]), "station", "The correct answer is 'station'"),
        
        // SENTENCES_COMPLETION
        new MultipleChoicesQuiz(11, QuizType.SENTENCES_COMPLETION, "I like flowers", shuffleArray(["すき", "わたし", "はな", "が", "は", "ほ"]), "わたしははながすき", "The correct answer is 「わたしははながすき」(I like flowers)"),
        new MultipleChoicesQuiz(12, QuizType.SENTENCES_COMPLETION, "I like cats", shuffleArray(["ねこ", "いぬ", "が", "すき", "は", "です"]), "ねこがすきです", "The correct answer is 「ねこがすきです」(I like cats)"),
        new MultipleChoicesQuiz(13, QuizType.SENTENCES_COMPLETION, "I go to school", shuffleArray(["わたし", "は", "がっこう", "に", "いきます", "いえ"]), "わたしはがっこうにいきます", "The correct answer is 「わたしはがっこうにいきます」(I go to school)"),
        new MultipleChoicesQuiz(14, QuizType.SENTENCES_COMPLETION, "I play with friends", shuffleArray(["ともだち", "と", "あそびます", "は", "が", "で"]), "ともだちとあそびます", "The correct answer is 「ともだちとあそびます」(I play with friends)"),
        new MultipleChoicesQuiz(15, QuizType.SENTENCES_COMPLETION, "I read a book", shuffleArray(["わたし", "は", "ほん", "を", "よみます", "が"]), "わたしはほんをよみます", "The correct answer is 「わたしはほんをよみます」(I read a book)"),
        new MultipleChoicesQuiz(16, QuizType.SENTENCES_COMPLETION, "There is a dog", shuffleArray(["いぬ", "が", "います", "ねこ", "は", "に"]), "いぬがいます", "The correct answer is 「いぬがいます」(There is a dog)"),
        new MultipleChoicesQuiz(17, QuizType.SENTENCES_COMPLETION, "I listen to music", shuffleArray(["わたし", "は", "おんがく", "を", "ききます", "が"]), "わたしはおんがくをききます", "The correct answer is 「わたしはおんがくをききます」(I listen to music)"),
        new MultipleChoicesQuiz(18, QuizType.SENTENCES_COMPLETION, "I study Japanese", shuffleArray(["わたし", "は", "にほんご", "を", "べんきょうします", "が"]), "わたしはにほんごをべんきょうします", "The correct answer is 「わたしはにほんごをべんきょうします」(I study Japanese)"),
        new MultipleChoicesQuiz(19, QuizType.SENTENCES_COMPLETION, "I meet my friend", shuffleArray(["わたし", "は", "ともだち", "に", "あいます", "が"]), "わたしはともだちにあいます", "The correct answer is 「わたしはともだちにあいます」(I meet my friend)"),
        new MultipleChoicesQuiz(20, QuizType.SENTENCES_COMPLETION, "I watch a movie", shuffleArray(["わたし", "は", "えいが", "を", "みます", "が"]), "わたしはえいがをみます", "The correct answer is 「わたしはえいがをみます」(I watch a movie)"),
        
        // CHARACTERS_LEARNING (N5 Vocabulary with yomikata)
        new MultipleChoicesQuiz(21, QuizType.CHARACTERS_LEARNING, "What is the meaning of '水' (みず)?", shuffleArray(["water", "fire", "earth", "wind"]), "water", "The correct answer is 'water'"),
        new MultipleChoicesQuiz(22, QuizType.CHARACTERS_LEARNING, "What is the meaning of '火' (ひ)?", shuffleArray(["fire", "water", "earth", "wind"]), "fire", "The correct answer is 'fire'"),
        new MultipleChoicesQuiz(23, QuizType.CHARACTERS_LEARNING, "What is the meaning of '風' (かぜ)?", shuffleArray(["wind", "water", "fire", "earth"]), "wind", "The correct answer is 'wind'"),
        new MultipleChoicesQuiz(24, QuizType.CHARACTERS_LEARNING, "What is the meaning of '土' (つち)?", shuffleArray(["earth", "water", "fire", "wind"]), "earth", "The correct answer is 'earth'"),
        new MultipleChoicesQuiz(25, QuizType.CHARACTERS_LEARNING, "What is the meaning of '山' (やま)?", shuffleArray(["mountain", "river", "sea", "forest"]), "mountain", "The correct answer is 'mountain'"),
        
        // SENTENCES_COMPLETION
        new MultipleChoicesQuiz(26, QuizType.SENTENCES_COMPLETION, "I eat an apple", shuffleArray(["わたし", "は", "りんご", "を", "たべます", "が"]), "わたしはりんごをたべます", "The correct answer is 「わたしはりんごをたべます」(I eat an apple)"),
        new MultipleChoicesQuiz(27, QuizType.SENTENCES_COMPLETION, "I buy a car", shuffleArray(["わたし", "は", "くるま", "を", "かいます", "が"]), "わたしはくるまをかいます", "The correct answer is 「わたしはくるまをかいます」(I buy a car)"),
        new MultipleChoicesQuiz(28, QuizType.SENTENCES_COMPLETION, "I go to the sea", shuffleArray(["わたし", "は", "うみ", "に", "いきます", "が"]), "わたしはうみにいきます", "The correct answer is 「わたしはうみにいきます」(I go to the sea)"),
        new MultipleChoicesQuiz(29, QuizType.SENTENCES_COMPLETION, "I eat vegetables", shuffleArray(["わたし", "は", "やさい", "を", "たべます", "が"]), "わたしはやさいをたべます", "The correct answer is 「わたしはやさいをたべます」(I eat vegetables)"),
        new MultipleChoicesQuiz(30, QuizType.SENTENCES_COMPLETION, "I buy a book", shuffleArray(["わたし", "は", "ほん", "を", "かいます", "が"]), "わたしはほんをかいます", "The correct answer is 「わたしはほんをかいます」(I buy a book)"),
        new MultipleChoicesQuiz(31, QuizType.CHARACTERS_LEARNING, "What is the meaning of '何' (なに)?", shuffleArray(["what", "who", "where", "when"]), "what", "The correct answer is 'what'"),
        new MultipleChoicesQuiz(32, QuizType.CHARACTERS_LEARNING, "What is the meaning of '誰' (だれ)?", shuffleArray(["who", "what", "where", "when"]), "who", "The correct answer is 'who'"),
        new MultipleChoicesQuiz(33, QuizType.CHARACTERS_LEARNING, "What is the meaning of 'どこ'?", shuffleArray(["where", "what", "who", "when"]), "where", "The correct answer is 'where'"),
        new MultipleChoicesQuiz(34, QuizType.CHARACTERS_LEARNING, "What is the meaning of 'いつ'?", shuffleArray(["when", "what", "who", "where"]), "when", "The correct answer is 'when'"),
        new MultipleChoicesQuiz(35, QuizType.CHARACTERS_LEARNING, "What is the meaning of 'どうして'?", shuffleArray(["why", "how", "what", "who"]), "why", "The correct answer is 'why'"),
        
        new MultipleChoicesQuiz(36, QuizType.SENTENCES_COMPLETION, "What is your name?", shuffleArray(["あなた", "の", "なまえ", "は", "なん", "です", "か"]), "あなたのなまえはなんですか", "The correct answer is 「あなたのなまえはなんですか」(What is your name?)"),
new MultipleChoicesQuiz(37, QuizType.SENTENCES_COMPLETION, "Where do you live?", shuffleArray(["あなた", "は", "どこ", "に", "すんで", "います", "か"]), "あなたはどこにすんでいますか", "The correct answer is 「あなたはどこにすんでいますか」(Where do you live?)"),
new MultipleChoicesQuiz(38, QuizType.SENTENCES_COMPLETION, "How old are you?", shuffleArray(["あなた", "は", "なんさい", "です", "か", "いくつ"]), "あなたはなんさいですか", "The correct answer is 「あなたはなんさいですか」(How old are you?)"),
new MultipleChoicesQuiz(39, QuizType.SENTENCES_COMPLETION, "What time is it?", shuffleArray(["いま", "なんじ", "です", "か", "は", "ですか"]), "いまなんじですか", "The correct answer is 「いまなんじですか」(What time is it?)"),
new MultipleChoicesQuiz(40, QuizType.SENTENCES_COMPLETION, "Why are you here?", shuffleArray(["あなた", "は", "どうして", "ここ", "に", "いる", "の", "です", "か"]), "あなたはどうしてここにいるのですか", "The correct answer is 「あなたはどうしてここにいるのですか」(Why are you here?)"),
        ]
    },
    lesson2: {
        quizzes: [
            new MultipleChoicesQuiz(1, QuizType.CHARACTERS_LEARNING, "What is the meaning of '空港' (くうこう)?", shuffleArray(["airport", "station", "bus stop", "port"]), "airport", "The correct answer is 'airport'"),
            new MultipleChoicesQuiz(2, QuizType.CHARACTERS_LEARNING, "What is the meaning of '飛行機' (ひこうき)?", shuffleArray(["airplane", "train", "bus", "car"]), "airplane", "The correct answer is 'airplane'"),
            new MultipleChoicesQuiz(3, QuizType.CHARACTERS_LEARNING, "What is the meaning of '電車' (でんしゃ)?", shuffleArray(["train", "car", "bicycle", "bus"]), "train", "The correct answer is 'train'"),
            new MultipleChoicesQuiz(4, QuizType.CHARACTERS_LEARNING, "What is the meaning of 'バス'?", shuffleArray(["bus", "car", "bicycle", "train"]), "bus", "The correct answer is 'bus'"),
            new MultipleChoicesQuiz(5, QuizType.CHARACTERS_LEARNING, "What is the meaning of 'タクシー'?", shuffleArray(["taxi", "bus", "car", "train"]), "taxi", "The correct answer is 'taxi'"),
            new MultipleChoicesQuiz(6, QuizType.CHARACTERS_LEARNING, "What is the meaning of '駅' (えき)?", shuffleArray(["station", "bus stop", "airport", "port"]), "station", "The correct answer is 'station'"),
            new MultipleChoicesQuiz(7, QuizType.CHARACTERS_LEARNING, "What is the meaning of '地図' (ちず)?", shuffleArray(["map", "ticket", "passport", "guidebook"]), "map", "The correct answer is 'map'"),
            new MultipleChoicesQuiz(8, QuizType.CHARACTERS_LEARNING, "What is the meaning of '切符' (きっぷ)?", shuffleArray(["ticket", "passport", "map", "guidebook"]), "ticket", "The correct answer is 'ticket'"),
            new MultipleChoicesQuiz(9, QuizType.CHARACTERS_LEARNING, "What is the meaning of 'パスポート'?", shuffleArray(["passport", "ticket", "map", "guidebook"]), "passport", "The correct answer is 'passport'"),
            new MultipleChoicesQuiz(10, QuizType.CHARACTERS_LEARNING, "What is the meaning of 'ガイドブック'?", shuffleArray(["guidebook", "map", "ticket", "passport"]), "guidebook", "The correct answer is 'guidebook'"),
            
            // SENTENCES_COMPLETION
            new MultipleChoicesQuiz(11, QuizType.SENTENCES_COMPLETION, "I need a map", shuffleArray(["が", "ほしい", "ちず", "です", "わたし", "に"]), "わたしはちずがほしいです", "The correct answer is 「わたしはちずがほしいです」(I need a map)"),
            new MultipleChoicesQuiz(12, QuizType.SENTENCES_COMPLETION, "Where is the station?", shuffleArray(["どこ", "です", "えき", "は", "に", "が"]), "えきはどこですか", "The correct answer is 「えきはどこですか」(Where is the station?)"),
            new MultipleChoicesQuiz(13, QuizType.SENTENCES_COMPLETION, "I want to go to the airport", shuffleArray(["に", "いきたい", "くうこう", "わたし", "は", "です"]), "わたしはくうこうにいきたいです", "The correct answer is 「わたしはくうこうにいきたいです」(I want to go to the airport)"),
            new MultipleChoicesQuiz(14, QuizType.SENTENCES_COMPLETION, "How much is the ticket?", shuffleArray(["いくら", "です", "きっぷ", "は", "が", "に"]), "きっぷはいくらですか", "The correct answer is 「きっぷはいくらですか」(How much is the ticket?)"),
            new MultipleChoicesQuiz(15, QuizType.SENTENCES_COMPLETION, "I need a taxi", shuffleArray(["が", "ほしい", "タクシー", "です", "わたし", "に"]), "わたしはタクシーがほしいです", "The correct answer is 「わたしはタクシーがほしいです」(I need a taxi)"),
            new MultipleChoicesQuiz(16, QuizType.SENTENCES_COMPLETION, "Where is the bus stop?", shuffleArray(["どこ", "です", "バスてい", "は", "に", "が"]), "バスていはどこですか", "The correct answer is 「バスていはどこですか」(Where is the bus stop?)"),
            new MultipleChoicesQuiz(17, QuizType.SENTENCES_COMPLETION, "I want to go to the hotel", shuffleArray(["に", "いきたい", "ホテル", "わたし", "は", "です"]), "わたしはホテルにいきたいです", "The correct answer is 「わたしはホテルにいきたいです」(I want to go to the hotel)"),
            new MultipleChoicesQuiz(18, QuizType.SENTENCES_COMPLETION, "How much is the fare?", shuffleArray(["いくら", "です", "りょうきん", "は", "が", "に"]), "りょうきんはいくらですか", "The correct answer is 「りょうきんはいくらですか」(How much is the fare?)"),
            new MultipleChoicesQuiz(19, QuizType.SENTENCES_COMPLETION, "I need a guidebook", shuffleArray(["が", "ほしい", "ガイドブック", "です", "わたし", "に"]), "わたしはガイドブックがほしいです", "The correct answer is 「わたしはガイドブックがほしいです」(I need a guidebook)"),
            new MultipleChoicesQuiz(20, QuizType.SENTENCES_COMPLETION, "Where is the airport?", shuffleArray(["どこ", "です", "くうこう", "は", "に", "が"]), "くうこうはどこですか", "The correct answer is 「くうこうはどこですか」(Where is the airport?)"),
            
            // CHARACTERS_LEARNING (Traveling Vocabulary with yomikata)
            new MultipleChoicesQuiz(21, QuizType.CHARACTERS_LEARNING, "What is the meaning of 'ホテル'?", shuffleArray(["hotel", "restaurant", "shop", "park"]), "hotel", "The correct answer is 'hotel'"),
            new MultipleChoicesQuiz(22, QuizType.CHARACTERS_LEARNING, "What is the meaning of 'レストラン'?", shuffleArray(["restaurant", "hotel", "shop", "park"]), "restaurant", "The correct answer is 'restaurant'"),
            new MultipleChoicesQuiz(23, QuizType.CHARACTERS_LEARNING, "What is the meaning of '店' (みせ)?", shuffleArray(["shop", "restaurant", "hotel", "park"]), "shop", "The correct answer is 'shop'"),
            new MultipleChoicesQuiz(24, QuizType.CHARACTERS_LEARNING, "What is the meaning of '公園' (こうえん)?", shuffleArray(["park", "shop", "restaurant", "hotel"]), "park", "The correct answer is 'park'"),
            new MultipleChoicesQuiz(25, QuizType.CHARACTERS_LEARNING, "What is the meaning of '病院' (びょういん)?", shuffleArray(["hospital", "clinic", "pharmacy", "doctor"]), "hospital", "The correct answer is 'hospital'"),
            
            // SENTENCES_COMPLETION
            new MultipleChoicesQuiz(26, QuizType.SENTENCES_COMPLETION, "I need a hotel", shuffleArray(["が", "ほしい", "ホテル", "です", "わたし", "に"]), "わたしはホテルがほしいです", "The correct answer is 「わたしはホテルがほしいです」(I need a hotel)"),
            new MultipleChoicesQuiz(27, QuizType.SENTENCES_COMPLETION, "Where is the restaurant?", shuffleArray(["どこ", "です", "レストラン", "は", "に", "が"]), "レストランはどこですか", "The correct answer is 「レストランはどこですか」(Where is the restaurant?)"),
            new MultipleChoicesQuiz(28, QuizType.SENTENCES_COMPLETION, "I want to go to the shop", shuffleArray(["に", "いきたい", "みせ", "わたし", "は", "です"]), "わたしはみせにいきたいです", "The correct answer is 「わたしはみせにいきたいです」(I want to go to the shop)"),
            new MultipleChoicesQuiz(29, QuizType.SENTENCES_COMPLETION, "How much is the meal?", shuffleArray(["いくら", "です", "しょくじ", "は", "が", "に"]), "しょくじはいくらですか", "The correct answer is 「しょくじはいくらですか」(How much is the meal?)"),
            new MultipleChoicesQuiz(30, QuizType.SENTENCES_COMPLETION, "I need a hospital", shuffleArray(["が", "ほしい", "びょういん", "です", "わたし", "に"]), "わたしはびょういんがほしいです", "The correct answer is 「わたしはびょういんがほしいです」(I need a hospital)")

        ]
    },
    lesson3: {
        quizzes: [
            // CHARACTERS_LEARNING (Food and Drink Vocabulary with yomikata)
            new MultipleChoicesQuiz(1, QuizType.CHARACTERS_LEARNING, "What is the meaning of '食べ物' (たべもの)?", shuffleArray(["food", "drink", "fruit", "vegetable"]), "food", "The correct answer is 'food'"),
            new MultipleChoicesQuiz(2, QuizType.CHARACTERS_LEARNING, "What is the meaning of '飲み物' (のみもの)?", shuffleArray(["drink", "food", "fruit", "vegetable"]), "drink", "The correct answer is 'drink'"),
            new MultipleChoicesQuiz(3, QuizType.CHARACTERS_LEARNING, "What is the meaning of '果物' (くだもの)?", shuffleArray(["fruit", "vegetable", "food", "drink"]), "fruit", "The correct answer is 'fruit'"),
            new MultipleChoicesQuiz(4, QuizType.CHARACTERS_LEARNING, "What is the meaning of '野菜' (やさい)?", shuffleArray(["vegetable", "fruit", "food", "drink"]), "vegetable", "The correct answer is 'vegetable'"),
            new MultipleChoicesQuiz(5, QuizType.CHARACTERS_LEARNING, "What is the meaning of 'ご飯' (ごはん)?", shuffleArray(["rice", "bread", "noodle", "soup"]), "rice", "The correct answer is 'rice'"),
            new MultipleChoicesQuiz(6, QuizType.CHARACTERS_LEARNING, "What is the meaning of 'パン'?", shuffleArray(["bread", "rice", "noodle", "soup"]), "bread", "The correct answer is 'bread'"),
            new MultipleChoicesQuiz(7, QuizType.CHARACTERS_LEARNING, "What is the meaning of '麺' (めん)?", shuffleArray(["noodle", "rice", "bread", "soup"]), "noodle", "The correct answer is 'noodle'"),
            new MultipleChoicesQuiz(8, QuizType.CHARACTERS_LEARNING, "What is the meaning of 'スープ'?", shuffleArray(["soup", "rice", "bread", "noodle"]), "soup", "The correct answer is 'soup'"),
            new MultipleChoicesQuiz(9, QuizType.CHARACTERS_LEARNING, "What is the meaning of '肉' (にく)?", shuffleArray(["meat", "fish", "chicken", "pork"]), "meat", "The correct answer is 'meat'"),
            new MultipleChoicesQuiz(10, QuizType.CHARACTERS_LEARNING, "What is the meaning of '魚' (さかな)?", shuffleArray(["fish", "meat", "chicken", "pork"]), "fish", "The correct answer is 'fish'"),
            
            // SENTENCES_COMPLETION
            new MultipleChoicesQuiz(11, QuizType.SENTENCES_COMPLETION, "I like apples", shuffleArray(["すき", "わたし", "りんご", "が", "は", "です", "たべます", "のみます"]), "わたしはりんごがすきです", "The correct answer is 「わたしはりんごがすきです」(I like apples)"),
            new MultipleChoicesQuiz(12, QuizType.SENTENCES_COMPLETION, "I eat rice", shuffleArray(["たべます", "わたし", "ごはん", "が", "は", "を", "すき", "のみます"]), "わたしはごはんをたべます", "The correct answer is 「わたしはごはんをたべます」(I eat rice)"),
            new MultipleChoicesQuiz(13, QuizType.SENTENCES_COMPLETION, "I drink water", shuffleArray(["のみます", "わたし", "みず", "が", "は", "を", "すき", "たべます"]), "わたしはみずをのみます", "The correct answer is 「わたしはみずをのみます」(I drink water)"),
            new MultipleChoicesQuiz(14, QuizType.SENTENCES_COMPLETION, "I want to eat sushi", shuffleArray(["たべたい", "すし", "わたし", "が", "は", "を", "のみます", "たべます"]), "わたしはすしをたべたいです", "The correct answer is 「わたしはすしをたべたいです」(I want to eat sushi)"),
            new MultipleChoicesQuiz(15, QuizType.SENTENCES_COMPLETION, "I like vegetables", shuffleArray(["すき", "わたし", "やさい", "が", "は", "です", "たべます", "のみます"]), "わたしはやさいがすきです", "The correct answer is 「わたしはやさいがすきです」(I like vegetables)"),
            new MultipleChoicesQuiz(16, QuizType.SENTENCES_COMPLETION, "I eat bread", shuffleArray(["たべます", "わたし", "パン", "が", "は", "を", "すき", "のみます"]), "わたしはパンをたべます", "The correct answer is 「わたしはパンをたべます」(I eat bread)"),
            new MultipleChoicesQuiz(17, QuizType.SENTENCES_COMPLETION, "I drink tea", shuffleArray(["のみます", "わたし", "おちゃ", "が", "は", "を", "すき", "たべます"]), "わたしはおちゃをのみます", "The correct answer is 「わたしはおちゃをのみます」(I drink tea)"),
            new MultipleChoicesQuiz(18, QuizType.SENTENCES_COMPLETION, "I want to eat meat", shuffleArray(["たべたい", "にく", "わたし", "が", "は", "を", "のみます", "たべます"]), "わたしはにくをたべたいです", "The correct answer is 「わたしはにくをたべたいです」(I want to eat meat)"),
            new MultipleChoicesQuiz(19, QuizType.SENTENCES_COMPLETION, "I like fish", shuffleArray(["すき", "わたし", "さかな", "が", "は", "です", "たべます", "のみます"]), "わたしはさかながすきです", "The correct answer is 「わたしはさかながすきです」(I like fish)"),
            new MultipleChoicesQuiz(20, QuizType.SENTENCES_COMPLETION, "I eat noodles", shuffleArray(["たべます", "わたし", "めん", "が", "は", "を", "すき", "のみます"]), "わたしはめんをたべます", "The correct answer is 「わたしはめんをたべます」(I eat noodles)"),
            
            // CHARACTERS_LEARNING (Food and Drink Vocabulary with yomikata)
            new MultipleChoicesQuiz(21, QuizType.CHARACTERS_LEARNING, "What is the meaning of 'お茶' (おちゃ)?", shuffleArray(["tea", "coffee", "juice", "water"]), "tea", "The correct answer is 'tea'"),
            new MultipleChoicesQuiz(22, QuizType.CHARACTERS_LEARNING, "What is the meaning of 'コーヒー'?", shuffleArray(["coffee", "tea", "juice", "water"]), "coffee", "The correct answer is 'coffee'"),
            new MultipleChoicesQuiz(23, QuizType.CHARACTERS_LEARNING, "What is the meaning of 'ジュース'?", shuffleArray(["juice", "coffee", "tea", "water"]), "juice", "The correct answer is 'juice'"),
            new MultipleChoicesQuiz(24, QuizType.CHARACTERS_LEARNING, "What is the meaning of '水' (みず)?", shuffleArray(["water", "coffee", "tea", "juice"]), "water", "The correct answer is 'water'"),
            new MultipleChoicesQuiz(25, QuizType.CHARACTERS_LEARNING, "What is the meaning of '牛乳' (ぎゅうにゅう)?", shuffleArray(["milk", "water", "juice", "tea"]), "milk", "The correct answer is 'milk'"),
            
            // SENTENCES_COMPLETION
            new MultipleChoicesQuiz(26, QuizType.SENTENCES_COMPLETION, "I need water", shuffleArray(["が", "ほしい", "みず", "です", "わたし", "に"]), "わたしはみずがほしいです", "The correct answer is 「わたしはみずがほしいです」(I need water)"),
            new MultipleChoicesQuiz(27, QuizType.SENTENCES_COMPLETION, "Where is the restaurant?", shuffleArray(["どこ", "です", "レストラン", "は", "に", "が"]), "レストランはどこですか", "The correct answer is 「レストランはどこですか」(Where is the restaurant?)"),
            new MultipleChoicesQuiz(28, QuizType.SENTENCES_COMPLETION, "I want to drink coffee", shuffleArray(["のみたい", "コーヒー", "わたし", "が", "は", "を"]), "わたしはコーヒーをのみたいです", "The correct answer is 「わたしはコーヒーをのみたいです」(I want to drink coffee)"),
            new MultipleChoicesQuiz(29, QuizType.SENTENCES_COMPLETION, "How much is the meal?", shuffleArray(["いくら", "です", "しょくじ", "は", "が", "に"]), "しょくじはいくらですか", "The correct answer is 「しょくじはいくらですか」(How much is the meal?)"),
            new MultipleChoicesQuiz(30, QuizType.SENTENCES_COMPLETION, "I need milk", shuffleArray(["が", "ほしい", "ぎゅうにゅう", "です", "わたし", "に"]), "わたしはぎゅうにゅうがほしいです", "The correct answer is 「わたしはぎゅうにゅうがほしいです」(I need milk)")
        ]
    }
}